#!/usr/bin/env bash
set -euo pipefail

# Cloudflare-origin hardening for the Hostinger VPS.
#
# Context: greighstudios.com, danielhipskind.com, fihaven.app, voteaxis.org and
# koasto.xyz are Cloudflare-proxied; the origin IP is nonetheless public because
# mail.<domain> must resolve straight to the box (mail cannot be proxied). So
# origin protection has to come from the firewall, not from IP secrecy.
#
# Run ON THE SERVER, as root. Dry-run by default:
#   ./origin-hardening.sh              # print the plan, change nothing
#   ./origin-hardening.sh --apply      # stage 1: close direct app ports
#   ./origin-hardening.sh --apply --with-443   # + restrict 443 to Cloudflare
#
# --with-443 is OPT-IN because it is only safe once every domain on this box is
# Cloudflare-proxied. As of the last audit lgenia.com was NOT — it has an A
# record pointing straight here, so a Cloudflare-only 443 rule would take it
# offline. Proxy lgenia.com first, then re-run with the flag.

APPLY=0
WITH_443=0
for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    --with-443) WITH_443=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done
run() { if [ "$APPLY" = 1 ]; then echo "  + $*"; "$@"; else echo "  [dry-run] $*"; fi; }

command -v ufw >/dev/null || { echo "❌ ufw not installed"; exit 1; }

# --- Guard: never proceed if SSH would be left unreachable ------------------
if ! ufw status | grep -qE '^22(/tcp)?[[:space:]]+ALLOW'; then
  echo "❌ No ufw ALLOW rule for port 22 — refusing to touch the firewall."
  exit 1
fi

# --- Cloudflare ranges ------------------------------------------------------
echo "→ Fetching Cloudflare IP ranges"
CF_V4="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)"
CF_V6="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)"
# Sanity-check before we act on them: a truncated fetch must not become a
# firewall that blocks Cloudflare itself.
[ "$(printf '%s\n' "$CF_V4" | grep -c '/')" -ge 10 ] || { echo "❌ CF v4 list looks wrong"; exit 1; }
[ "$(printf '%s\n' "$CF_V6" | grep -c '/')" -ge 3 ]  || { echo "❌ CF v6 list looks wrong"; exit 1; }
echo "  $(printf '%s\n' "$CF_V4" | grep -c '/') v4 + $(printf '%s\n' "$CF_V6" | grep -c '/') v6 ranges"

# --- Stage 1: close directly-exposed app ports ------------------------------
# 3000/3001/3002 are Next/node apps that nginx already reverse-proxies. Left
# open they are a straight Cloudflare bypass: hit http://<origin>:3000 and you
# reach the app with no WAF, no rate limit, and no TLS.
echo
echo "→ Stage 1: closing direct app ports (nginx keeps serving them)"
# ufw records these in two spellings ("3000" and "3002/tcp") depending on how
# each was originally added, and deleting one form leaves the other in place.
for port in 3000 3001 3002; do
  closed=1
  for form in "$port" "$port/tcp"; do
    if ufw status | grep -qE "^${form//\//\\/}[[:space:]]+ALLOW"; then
      run ufw --force delete allow "$form"
      closed=0
    fi
  done
  [ "$closed" = 1 ] && echo "  · $port already closed"
done

# --- Stage 2 (opt-in): 443 from Cloudflare only -----------------------------
if [ "$WITH_443" = 1 ]; then
  echo
  echo "→ Stage 2: restricting 443 to Cloudflare"
  echo "  Port 80 is deliberately LEFT OPEN — certbot renews the mail.* certs"
  echo "  over HTTP-01, and those hosts are not proxied, so Let's Encrypt must"
  echo "  reach port 80 directly."
  # Drop the broad 443 allows (several duplicates exist from old profiles).
  for rule in "443" "443/tcp" "Nginx Full"; do
    while ufw status | grep -qE "^${rule}[[:space:]]+ALLOW IN[[:space:]]+Anywhere"; do
      run ufw --force delete allow "$rule" || break
    done
  done
  while read -r cidr; do
    [ -n "$cidr" ] && run ufw allow from "$cidr" to any port 443 proto tcp comment 'cloudflare-origin'
  done <<< "$CF_V4"
  while read -r cidr; do
    [ -n "$cidr" ] && run ufw allow from "$cidr" to any port 443 proto tcp comment 'cloudflare-origin'
  done <<< "$CF_V6"
else
  echo
  echo "→ Stage 2 skipped (no --with-443). Prerequisite: lgenia.com must be"
  echo "  Cloudflare-proxied first, or this rule takes it offline."
fi

# --- nginx: restore the real client IP --------------------------------------
# Without this every request logs as a Cloudflare IP, and any rate limiting or
# abuse blocking keys off the proxy instead of the visitor.
echo
echo "→ Writing /etc/nginx/conf.d/cloudflare-realip.conf"
REALIP=/etc/nginx/conf.d/cloudflare-realip.conf
if [ "$APPLY" = 1 ]; then
  {
    echo "# Generated by deploy/origin-hardening.sh — re-run when CF ranges change."
    printf '%s\n' "$CF_V4" | sed 's#^#set_real_ip_from #; s#$#;#'
    printf '%s\n' "$CF_V6" | sed 's#^#set_real_ip_from #; s#$#;#'
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
  } > "$REALIP"
  nginx -t && systemctl reload nginx
  echo "  ✅ nginx reloaded"
else
  echo "  [dry-run] would write $REALIP and reload nginx"
fi

echo
echo "→ Remaining items this script deliberately does NOT change:"
echo "   · vsftpd is active with 20/21/990 + 40000-50000 open to the world."
echo "     FTP credentials cross the wire in the clear. Deploys use rsync over"
echo "     SSH, so this is very likely disable-able: systemctl disable --now vsftpd"
echo "   · sshd has PermitRootLogin yes with password auth, exposed on 22."
echo "     deploy.sh authenticates with SSH_PASSWORD as root, so switching to"
echo "     key-only auth means generating a key and setting SSH_KEY first."
echo "   · Port 1022 and 5222 are open; confirm what needs them before closing."
echo
[ "$APPLY" = 1 ] && echo "✅ Applied." || echo "ℹ️  Dry run only — nothing changed. Re-run with --apply."
